Update json-lint.yml

diff --git a/.github/workflows/json-lint.yml b/.github/workflows/json-lint.yml
--- a/.github/workflows/json-lint.yml
+++ b/.github/workflows/json-lint.yml
@@ -26,4 +26,8 @@ jobs:
 
     - name: Run jsonlint
       run: |
-        find json -name "*.json" -exec jsonlint  {} \;
+        find json -name "*.json" -exec jsonlint --quiet {} \;
+        if [ $? -ne 0 ]; then
+          echo "JSON linting failed"
+          exit 1
+        fi
